### ISSUE TITLE
"Auto" doesn't work with opentelemetry-javaagent v0.9.0

### ISSUE THREAD

**Issue by kewats** [GoogleCloudPlatform/opentelemetry-operations-java#47] opened 2020-11-04 03:02 UTC
I am trying to use opentelemetry javaagent and export traces to cloud trace. I am running into "No span exporter found" issues:

```
java -Dotel.exporter.jar=path/to/exporter-trace-0.9.1.jar  -javaagent:path/to/opentelemetry-javaagent-0.9.0-all.jar -jar path/to/myApp.jar
[opentelemetry.auto.trace 2020-11-04 08:08:19:881 +0530] [main] WARN io.opentelemetry.javaagent.tooling.TracerInstaller - No span exporter found in path/to/exporter-trace-0.9.1.jar
[opentelemetry.auto.trace 2020-11-04 08:08:19:882 +0530] [main] WARN io.opentelemetry.javaagent.tooling.TracerInstaller - No valid exporter found. Tracing will run but spans are dropped
[opentelemetry.auto.trace 2020-11-04 08:08:19:901 +0530] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 0.9.0
Hello world
[opentelemetry.auto.trace 2020-11-04 08:08:19:916 +0530] [opentelemetry-exec-shutdown-hook] WARN io.opentelemetry.javaagent.tooling.CommonTaskExecutor - Periodic task scheduler is shutdown. Will not run: cleaner for com.blogspot.mydailyjava.weaklockfree.WeakConcurrentMap@7d775612
```
Any suggestions on what could I be missing here or ways to investigate this further?

**Comment by nilebox** [comment] 2020-11-04 03:08
Hi @kewats! It seems that you're passing the wrong jar in `otel.exporter.jar=...`.
You need to pass path to [`exporter-auto`](https://mvnrepository.com/artifact/com.google.cloud.opentelemetry/exporter-auto/0.9.1) rather than `exporter-trace`.

See [README](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/master/exporters/auto/README.md)

Feel free to reopen if you still have issues with using it.

**Comment by kewats** [comment] 2020-11-04 03:42
Hi @nilebox, thanks for you response. I tried with exporter-auto too, but I'm running into the same problem.
```
java -Dotel.exporter.jar=path/to/exporter-auto-0.9.1.jar  -javaagent:path/to/opentelemetry-javaagent-0.9.0-all.jar -jar path/to/myApp.jar
[opentelemetry.auto.trace 2020-11-04 09:06:32:199 +0530] [main] WARN io.opentelemetry.javaagent.tooling.TracerInstaller - No span exporter found in path/to/exporter-auto-0.9.1.jar
[opentelemetry.auto.trace 2020-11-04 09:06:32:200 +0530] [main] WARN io.opentelemetry.javaagent.tooling.TracerInstaller - No valid exporter found. Tracing will run but spans are dropped
[opentelemetry.auto.trace 2020-11-04 09:06:32:220 +0530] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 0.9.0
Hello world
[opentelemetry.auto.trace 2020-11-04 09:06:32:234 +0530] [opentelemetry-exec-shutdown-hook] WARN io.opentelemetry.javaagent.tooling.CommonTaskExecutor - Periodic task scheduler is shutdown. Will not run: cleaner for com.blogspot.mydailyjava.weaklockfree.WeakConcurrentMap@7d3ec58f
```
I also looked at https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/master/build.gradle to see if I am using the wrong versions. It seems we need to use 0.8.0 of javaagent with 0.9.1 of exporter-auto. However, that leads to `Caused by: java.lang.ClassNotFoundException: com.google.cloud.opentelemetry.trace.TraceExporter`
Any suggestions on this?

**Comment by nilebox** [comment] 2020-11-04 03:52
By looking at the [code in java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/c931b1b85a508d25583bbbeb7e92dcf2fa9da367/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/TracerInstaller.java#L136-L144), it requires Factory implementing `io.opentelemetry.javaagent.spi.exporter.SpanExporterFactory`, whereas our code implements [io.opentelemetry.javaagent.tooling.exporter.SpanExporterFactory](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/fb7b39ac5d67f011f3972c6354f7b0470fb56752/exporters/auto/src/main/java/com/google/cloud/opentelemetry/auto/GoogleCloudSpanExporterFactory.java#L6).

This incompatibility is caused by this PR https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1187

This is easy to fix:
- Update dependency from 0.8.0 to 0.9.1: https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/fb7b39ac5d67f011f3972c6354f7b0470fb56752/build.gradle#L27
- Fix compilation by updating the interface.

The bigger problem is that Java agent tooling wasn't released in sync with SDK, that's why we have inconsistent dependency now.

**Comment by nilebox** [comment] 2020-11-04 03:52
@kewats feel free to submit a PR fixing this issue if that's urgent.

**Comment by kewats** [comment] 2020-11-04 04:42
Thanks @nilebox for the insight. I will submit a PR soon.

**Comment by kewats** [comment] 2020-11-04 11:14
@nilebox Even after this change and on using the exporter-auto generated with it, I still get this:
```
Caused by: java.lang.NoClassDefFoundError: com/google/cloud/opentelemetry/trace/TraceExporter
	at com.google.cloud.opentelemetry.auto.GoogleCloudSpanExporterFactory.fromConfig(GoogleCloudSpanExporterFactory.java:15)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExporter(TracerInstaller.java:181)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExportersFromJar(TracerInstaller.java:155)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installAgentTracer(TracerInstaller.java:51)
	... 18 more
Caused by: java.lang.ClassNotFoundException: com.google.cloud.opentelemetry.trace.TraceExporter
	at io.opentelemetry.javaagent.tooling.ExporterClassLoader.findClass(ExporterClassLoader.java:80)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 22 more
```
Am I missing something more here that needs to be fixed?

**Comment by nilebox** [comment] 2020-11-05 03:59
@kewats Looks like the `exporter-trace` jar is missing in your classpath for some reason.
To be clear, you need both `exporter-trace` (exporter implementation) and `exporter-auto` (javaagent integration) available in your classpath.

**Comment by kewats** [comment] 2020-11-05 05:57
@nilebox Looks like we need to supply exporter-trace as xbootclasspath for the agent to pick it up. However, it seems this too is not sufficient.

```
java -Xbootclasspath/a:path/to/opentelemetry-operations-java/exporters/trace/build/libs/exporter-trace-0.10.0-SNAPSHOT.jar -Dotel.exporter.jar=path/to/opentelemetry-operations-java-auto-fix/exporters/auto/build/libs/exporter-auto-0.10.0-SNAPSHOT.jar -javaagent:path/to/opentelemetry-javaagent-0.9.0-all.jar -jar path/to/myApp.jar

[opentelemetry.auto.trace 2020-11-05 11:23:02:018 +0530] [main] ERROR io.opentelemetry.javaagent.bootstrap.AgentInitializer - Throwable thrown while installing the agent tracer
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.installAgentTracer(AgentInitializer.java:162)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:64)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: io/opentelemetry/sdk/trace/export/SpanExporter
	at java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1008)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:407)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.google.cloud.opentelemetry.auto.GoogleCloudSpanExporterFactory.fromConfig(GoogleCloudSpanExporterFactory.java:15)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExporter(TracerInstaller.java:181)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installExportersFromJar(TracerInstaller.java:155)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installAgentTracer(TracerInstaller.java:51)
	... 18 more
```

**Comment by nilebox** [comment] 2020-11-05 06:06
> NoClassDefFoundError: io/opentelemetry/sdk/trace/export/SpanExporter

@kewats now you're missing `opentelemetry-sdk` (see [SpanExporter.java](https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/export/SpanExporter.java))

You need all other dependencies in https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/fb7b39ac5d67f011f3972c6354f7b0470fb56752/build.gradle#L33-L46 as well, so I would just suggest to build an "uber jar"  in your `path/to/myApp.jar` which will include all dependencies.

**Comment by nilebox** [comment] 2020-11-05 06:11
Created an issue #50 for addressing this on our side.

**Closed** 2020-11-05 06:12 UTC
